# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8089
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # 连接数满后的排队数，默认为100
    accept-count: 1000
    threads:
      # tomcat最大线程数，默认为200
      max: 800
      # Tomcat启动初始化的线程数，默认值10
      min-spare: 100

# 日志配置
logging:
  level:
    com.ruoyi: debug
    org.springframework: warn

  
# Spring配置
spring:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  web:
    resources:
      # 定义静态资源路径
      static-locations: file:///Users/yang/Project/github/RuoYi-Vue3/dist

proxy:
  solr:
    # 前端请求地址
    servlet_url: /prod-api/*
    # 转发地址
    target_url: http://localhost:8080/

